---
title: "Peru: Plotting cumulative change of Ministers and proportion of seats in Congress, 2001-2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
library(tidyverse)
library(readxl)
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
data_peru1 <- read_excel("Count authorities.xlsx", sheet = "R count")
data_peru_cong <- read_excel("Count authorities.xlsx", sheet = "R general")
```

## Plotting cumulative change of Ministers, 2001-2022

```{r}
data_peru1 %>% 
  ggplot(aes(N_month, Cumulative)) + 
  geom_area(fill = "dodgerblue4") + 
  xlab("Governmental months") +
  ylab("Cumulative change of Ministers") +
  labs(caption = "(*) Current government term \n Source: 'Diario Oficial El Peruano' web page (collected of February 13th, 2022)") +
  ggtitle("Cumulative change of Ministers per month on each government, 2001-2022") + 
  facet_wrap(vars(`Government_period`), strip.position = "top", nrow = 1) + 
  theme(plot.title = element_text(hjust = 0.5),
        plot.caption = element_text(hjust = 0.5)) +
  scale_x_continuous(breaks = seq(from = 0, to = 60, by = 10)) +
  ylim(0, 150)
```

## Plotting proportion of seats in Congress, 2001-2022

```{r}
data_peru_cong %>% 
  ggplot(aes(x = President, y = Proportion)) + 
  geom_col(aes(fill = Seats)) +
  ggtitle("Proportion of seats in Congress, 2001-2022") + 
   theme(plot.title = element_text(hjust = 0.5),
         plot.caption = element_text(hjust = 0.5)) +
  geom_abline(slope=0, intercept=0.34,  col = "red", lty=5, size=0.73) +
  scale_fill_manual(values = c("grey60", "dodgerblue4") ) +
  labs(x = "Presidents", 
       y = "Proportion",
       caption = "(*) The red dotted vertical line represents the minimum votes required (i.e., 34%) to preserve the Presidency \n if a ouster caucus is proposed by the Congress \n Source: Observatory of Governance - National Jury of Elections of Peru (collected of February 15th, 2022)") +
  coord_flip()
```
